--------------------------------------------------------
--  DDL for Table FACT
--------------------------------------------------------

CREATE TABLE "TESTER"."FACT"
(	"GENID" VARCHAR2(255 BYTE),
     "BIDID" VARCHAR2(255 BYTE),
     "CATEGB" VARCHAR2(50 BYTE),
     "CATEDETAIL" VARCHAR2(50 BYTE),
     "TIMEGB" VARCHAR2(50 BYTE),
     "TRADETIME" VARCHAR2(50 BYTE),
     "CHGREASON" VARCHAR2(255 BYTE)
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "USERS" ;

COMMENT ON COLUMN "TESTER"."FACT"."GENID" IS '발전기ID';
COMMENT ON TABLE "TESTER"."FACT"  IS 'fact';
--------------------------------------------------------
--  DDL for Index FACT_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTER"."FACT_PK" ON "TESTER"."FACT" ("GENID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FACT
--------------------------------------------------------

ALTER TABLE "TESTER"."FACT" MODIFY ("GENID" NOT NULL ENABLE);
ALTER TABLE "TESTER"."FACT" ADD CONSTRAINT "FACT_PK" PRIMARY KEY ("GENID")
    USING INDEX "TESTER"."FACT_PK"  ENABLE;


--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

CREATE TABLE "TESTER"."PROFILE"
(	"GENDID" VARCHAR2(4 BYTE),
     "TRADEDAY" VARCHAR2(8 BYTE),
     "REGDATE" VARCHAR2(8 BYTE),
     "REGRID" VARCHAR2(255 BYTE),
     "BIDREGDATE" VARCHAR2(8 BYTE),
     "BIDUSERID" VARCHAR2(255 BYTE),
     "BIDID" VARCHAR2(255 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

COMMENT ON COLUMN "TESTER"."PROFILE"."GENDID" IS '발전기ID';
   COMMENT ON COLUMN "TESTER"."PROFILE"."TRADEDAY" IS '거래일자';
   COMMENT ON COLUMN "TESTER"."PROFILE"."REGDATE" IS '등록일시';
   COMMENT ON COLUMN "TESTER"."PROFILE"."REGRID" IS '등록자ID';
   COMMENT ON COLUMN "TESTER"."PROFILE"."BIDREGDATE" IS '입찰등록일시';
   COMMENT ON COLUMN "TESTER"."PROFILE"."BIDUSERID" IS '입찰자ID';
   COMMENT ON TABLE "TESTER"."PROFILE"  IS 'profile';
--------------------------------------------------------
--  DDL for Index PROFILE_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTER"."PROFILE_PK" ON "TESTER"."PROFILE" ("GENDID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROFILE
--------------------------------------------------------

ALTER TABLE "TESTER"."PROFILE" MODIFY ("GENDID" NOT NULL ENABLE);
ALTER TABLE "TESTER"."PROFILE" MODIFY ("TRADEDAY" NOT NULL ENABLE);
ALTER TABLE "TESTER"."PROFILE" MODIFY ("REGDATE" NOT NULL ENABLE);
ALTER TABLE "TESTER"."PROFILE" MODIFY ("REGRID" NOT NULL ENABLE);
ALTER TABLE "TESTER"."PROFILE" MODIFY ("BIDREGDATE" NOT NULL ENABLE);
ALTER TABLE "TESTER"."PROFILE" MODIFY ("BIDUSERID" NOT NULL ENABLE);
ALTER TABLE "TESTER"."PROFILE" ADD CONSTRAINT "PROFILE_PK" PRIMARY KEY ("GENDID")
    USING INDEX "TESTER"."PROFILE_PK"  ENABLE;
